1. Imports AND Load Expression Matrix

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("expression_matrix.csv")
df.head()

,id,1996-105,1997-042,2000-025,2001-139,2003-035,2009-039,2012-067,2016-016,2016-023,2016-051,2017-012,2017-016,2017-041,2017-056,2017-059,2017-079
0,ENST00000000233.10,1281.692845,1251.407984,1414.602337,1099.415873,1233.101499,1309.356033,9.240227e+02,1173.827211,724.477280,726.270770,1127.172465,907.471334,1163.328172,1002.182380,918.387294,992.983120
1,ENST00000000412.8,1667.686937,909.045222,1336.369763,1416.138726,1269.099822,1179.018010,1.847958e+03,1543.639816,1394.528115,1360.870018,1405.917463,1092.914020,1062.317120,1357.515729,1393.128925,1090.078976
2,ENST00000000442.11,479.058400,670.548177,414.396868,863.391087,249.780076,283.223750,5.413267e+02,366.229490,551.800080,4.786482,522.832672,392.621628,663.922214,218.797000,180.490709,275.508388
3,ENST00000001008.6,2376.694548,2406.452695,3345.467859,1926.688739,1929.752350,2784.686843,8.072652e+03,2569.550934,11068.406440,4928.977228,2549.095513,1314.664179,2603.472841,1933.153208,2928.400601,2217.288089
4,ENST00000001146.6,33.788617,129.158743,0.000000,51.600469,0.000000,0.000000,1.900000e-08,93.232187,0.000000,34.132429,0.000000,19.312345,30.877795,0.000000,0.000000,89.611895

2. Log₂ Normalization

In [ ]:
ids = df.iloc[:, 0]
expr = df.iloc[:, 1:]

log2_expr = np.log2(expr + 1)

log2_df = pd.concat([ids, log2_expr], axis=1)
log2_df.head()

,id,1996-105,1997-042,2000-025,2001-139,2003-035,2009-039,2012-067,2016-016,2016-023,2016-051,2017-012,2017-016,2017-041,2017-056,2017-059,2017-079
0,ENST00000000233.10,10.324960,10.290489,10.467200,10.103833,10.269245,10.355743,9.853345e+00,10.198233,9.502787,9.506349,10.139772,9.827297,10.185282,9.970368,9.844529,9.957078
1,ENST00000000412.8,10.704498,9.829794,10.385183,10.468765,10.310726,10.204593,1.085250e+01,10.593055,10.446595,10.411373,10.458322,10.095284,10.054356,10.407816,10.445148,10.091540
2,ENST00000000442.11,8.907066,9.391347,8.698347,9.755540,7.970279,8.150883,9.083019e+00,8.520538,9.110614,2.532687,9.032962,8.620666,9.377042,7.780028,7.503752,8.111179
3,ENST00000001008.6,11.215348,11.233292,11.708423,10.912656,10.914947,11.443817,1.297901e+01,11.327862,13.434290,12.267365,11.316336,10.361576,11.346776,10.917486,11.516390,11.115231
4,ENST00000001146.6,5.120543,7.024128,0.000000,5.717004,0.000000,0.000000,2.741121e-08,6.558148,0.000000,5.134731,0.000000,4.344285,4.994480,0.000000,0.000000,6.501629

3. Save Output

In [ ]:
log2_df.to_csv("expression_matrix_log2.csv", index=False)