This notebook performs:

- Probe ID → Gene Symbol conversion (Microarray: AD, MS)
- ENSEMBL → Gene Symbol conversion (RNA-Seq: PD, HD)
- Duplicate removal via gene-level aggregation
- Saving harmonized datasets

**3. ID Harmonization (gene symbols)**

AD and MS datasets (microarray)

probe IDs -> Gene Symbols

Imports

In [ ]:
import pandas as pd

Load data + GPL

In [ ]:
# Load expression matrices
ad = pd.read_csv("AD_expression_matrix.csv", index_col=0)
ms = pd.read_csv("MS_expression_matrix.csv", index_col=0)

# Load GPL570 annotation
gpl = pd.read_csv("GPL570-55999.txt", sep="\t", comment="#")

# Keep only probe ID and Gene Symbol
gpl = gpl[['ID', 'Gene Symbol']].dropna()
gpl = gpl[gpl['Gene Symbol'] != '']
gpl = gpl.rename(columns={'ID': 'probe_id', 'Gene Symbol': 'gene_symbol'})

# Create mapping
probe_to_gene = dict(zip(gpl['probe_id'], gpl['gene_symbol']))

/tmp/ipython-input-4040058444.py:6: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  gpl = pd.read_csv("GPL570-55999.txt", sep="\t", comment="#")

In [ ]:
#AD mapping
ad['gene_symbol'] = ad.index.map(probe_to_gene)
ad = ad.dropna(subset=['gene_symbol'])
ad = ad.groupby('gene_symbol').mean()

In [ ]:
#MS mapping
ms['gene_symbol'] = ms.index.map(probe_to_gene)
ms = ms.dropna(subset=['gene_symbol'])
ms = ms.groupby('gene_symbol').mean()

In [ ]:
#Save ad/ms
ad.to_csv("AD_geneSymbol.csv")
ms.to_csv("MS_geneSymbol.csv")

PD and HD datasets (affymetrix)

ENSMBL IDs -> Gene Symbols

In [ ]:
!pip install mygene

Collecting mygene
  Downloading mygene-3.2.2-py2.py3-none-any.whl.metadata (10 kB)
Collecting biothings-client>=0.2.6 (from mygene)
  Downloading biothings_client-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: httpx>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from biothings-client>=0.2.6->mygene) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.22.0->biothings-client>=0.2.6->mygene) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.22.0->biothings-client>=0.2.6->mygene) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.22.0->biothings-client>=0.2.6->mygene) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.22.0->biothings-client>=0.2.6->mygene) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.22.0->biothings-client>=0.2.6->mygene) (0.16.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx>=0.22.0->biothings-client>=0.2.6->mygene) (4.15.0)
Downloading mygene-3.2.2-py2.py3-none-any.whl (5.4 kB)
Downloading biothings_client-0.4.1-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 1.2 MB/s eta 0:00:00
Installing collected packages: biothings-client, mygene
Successfully installed biothings-client-0.4.1 mygene-3.2.2

In [ ]:
import mygene
mg = mygene.MyGeneInfo()

In [ ]:
def ensembl_to_symbol(df):
    genes = df.index.str.split('.').str[0]  # remove version numbers
    res = mg.querymany(
        genes.tolist(),
        scopes="ensembl.gene",
        fields="symbol",
        species="human"
    )
    mapping = {r['query']: r.get('symbol') for r in res if 'symbol' in r}
    df['gene_symbol'] = genes.map(mapping)
    df = df.dropna(subset=['gene_symbol'])
    return df.groupby('gene_symbol').mean()

In [ ]:
hd = pd.read_csv("HD_expression_matrix.csv", index_col=0)
hd = ensembl_to_symbol(hd)

WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
INFO:biothings.client:querying 1-1000 ...
INFO:biothings.client:querying 1001-2000 ...
INFO:biothings.client:querying 2001-3000 ...
INFO:biothings.client:querying 3001-4000 ...
INFO:biothings.client:querying 4001-5000 ...
INFO:biothings.client:querying 5001-6000 ...
INFO:biothings.client:querying 6001-7000 ...
INFO:biothings.client:querying 7001-8000 ...
INFO:biothings.client:querying 8001-9000 ...
INFO:biothings.client:querying 9001-10000 ...
INFO:biothings.client:querying 10001-11000 ...
INFO:biothings.client:querying 11001-12000 ...
INFO:biothings.client:querying 12001-13000 ...
INFO:biothings.client:querying 13001-14000 ...
INFO:biothings.client:querying 14001-15000 ...
INFO:biothings.client:querying 15001-16000 ...
INFO:biothings.client:querying 16001-17000 ...
INFO:biothings.client:querying 17001-18000 ...
INFO:biothings.client:querying 18001-19000 ...
INFO:biothings.client:querying 19001-20000 ...
INFO:biothings.client:querying 20001-21000 ...
INFO:biothings.client:querying 21001-22000 ...
INFO:biothings.client:querying 22001-23000 ...
INFO:biothings.client:querying 23001-24000 ...
INFO:biothings.client:querying 24001-25000 ...
INFO:biothings.client:querying 25001-26000 ...
INFO:biothings.client:querying 26001-27000 ...
INFO:biothings.client:querying 27001-28000 ...
INFO:biothings.client:querying 28001-28087 ...
INFO:biothings.client:Finished.
WARNING:biothings.client:13 input query terms found dup hits:	[('ENSG00000175711', 2), ('ENSG00000188660', 2), ('ENSG00000215156', 2), ('ENSG00000226506', 2), ('E
WARNING:biothings.client:1989 input query terms found no hit:	['ENSG00000002079', 'ENSG00000005955', 'ENSG00000006075', 'ENSG00000006114', 'ENSG00000017373', 'ENS
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [ ]:
def clean_gene_symbols(df):
    df = df.copy()
    df.index = (
        df.index
        .astype(str)
        .str.upper()  # fix case
        .str.strip()  # remove spaces
        .str.split("///")  # handle Affy multi-mapping
        .str[0]
    )
    df = df[~df.index.isna()]
    df = df[df.index != ""]
    return df

In [ ]:
pd_ds.index = pd_ds.index.str.split('.').str[0]
hd.index = hd.index.str.split('.').str[0]

In [ ]:
pd_raw.index = pd_raw.index.str.split('.').str[0]

In [ ]:
import mygene
import pandas as pd

mg = mygene.MyGeneInfo()

def enst_to_symbol(df):
    """
    Convert ENSEMBL transcript IDs (ENST) to gene symbols
    """
    enst_ids = df.index.tolist()

    query = mg.querymany(
        enst_ids,
        scopes="ensembl.transcript",
        fields="symbol",
        species="human"
    )

    mapping = {}
    for item in query:
        if "query" in item and "symbol" in item:
            mapping[item["query"]] = item["symbol"]

    df = df[df.index.isin(mapping.keys())]
    df.index = df.index.map(mapping)
    df.index.name = "gene_symbol"

    return df

In [ ]:
pd_ds = enst_to_symbol(pd_raw)

WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
INFO:biothings.client:querying 1-1000 ...
INFO:biothings.client:querying 1001-2000 ...
INFO:biothings.client:querying 2001-3000 ...
INFO:biothings.client:querying 3001-4000 ...
INFO:biothings.client:querying 4001-5000 ...
INFO:biothings.client:querying 5001-6000 ...
INFO:biothings.client:querying 6001-7000 ...
INFO:biothings.client:querying 7001-8000 ...
INFO:biothings.client:querying 8001-9000 ...
INFO:biothings.client:querying 9001-10000 ...
INFO:biothings.client:querying 10001-11000 ...
INFO:biothings.client:querying 11001-12000 ...
INFO:biothings.client:querying 12001-13000 ...
INFO:biothings.client:querying 13001-14000 ...
INFO:biothings.client:querying 14001-15000 ...
INFO:biothings.client:querying 15001-16000 ...
INFO:biothings.client:querying 16001-17000 ...
INFO:biothings.client:querying 17001-18000 ...
INFO:biothings.client:querying 18001-19000 ...
INFO:biothings.client:querying 19001-20000 ...
INFO:biothings.client:querying 20001-21000 ...
INFO:biothings.client:querying 21001-22000 ...
INFO:biothings.client:querying 22001-23000 ...
INFO:biothings.client:querying 23001-24000 ...
INFO:biothings.client:querying 24001-25000 ...
INFO:biothings.client:querying 25001-26000 ...
INFO:biothings.client:querying 26001-27000 ...
INFO:biothings.client:querying 27001-28000 ...
INFO:biothings.client:querying 28001-29000 ...
INFO:biothings.client:querying 29001-30000 ...
INFO:biothings.client:querying 30001-31000 ...
INFO:biothings.client:querying 31001-32000 ...
INFO:biothings.client:querying 32001-33000 ...
INFO:biothings.client:querying 33001-34000 ...
INFO:biothings.client:querying 34001-35000 ...
INFO:biothings.client:querying 35001-36000 ...
INFO:biothings.client:querying 36001-37000 ...
INFO:biothings.client:querying 37001-38000 ...
INFO:biothings.client:querying 38001-39000 ...
INFO:biothings.client:querying 39001-40000 ...
INFO:biothings.client:querying 40001-41000 ...
INFO:biothings.client:querying 41001-42000 ...
INFO:biothings.client:querying 42001-43000 ...
INFO:biothings.client:querying 43001-44000 ...
INFO:biothings.client:querying 44001-45000 ...
INFO:biothings.client:querying 45001-46000 ...
INFO:biothings.client:querying 46001-47000 ...
INFO:biothings.client:querying 47001-48000 ...
INFO:biothings.client:querying 48001-49000 ...
INFO:biothings.client:querying 49001-50000 ...
INFO:biothings.client:querying 50001-51000 ...
INFO:biothings.client:querying 51001-52000 ...
INFO:biothings.client:querying 52001-53000 ...
INFO:biothings.client:querying 53001-54000 ...
INFO:biothings.client:querying 54001-55000 ...
INFO:biothings.client:querying 55001-56000 ...
INFO:biothings.client:querying 56001-57000 ...
INFO:biothings.client:querying 57001-58000 ...
INFO:biothings.client:querying 58001-59000 ...
INFO:biothings.client:querying 59001-60000 ...
INFO:biothings.client:querying 60001-61000 ...
INFO:biothings.client:querying 61001-62000 ...
INFO:biothings.client:querying 62001-63000 ...
INFO:biothings.client:querying 63001-64000 ...
INFO:biothings.client:querying 64001-65000 ...
INFO:biothings.client:querying 65001-66000 ...
INFO:biothings.client:querying 66001-67000 ...
INFO:biothings.client:querying 67001-68000 ...
INFO:biothings.client:querying 68001-69000 ...
INFO:biothings.client:querying 69001-70000 ...
INFO:biothings.client:querying 70001-71000 ...
INFO:biothings.client:querying 71001-72000 ...
INFO:biothings.client:querying 72001-73000 ...
INFO:biothings.client:querying 73001-74000 ...
INFO:biothings.client:querying 74001-75000 ...
INFO:biothings.client:querying 75001-76000 ...
INFO:biothings.client:querying 76001-77000 ...
INFO:biothings.client:querying 77001-78000 ...
INFO:biothings.client:querying 78001-79000 ...
INFO:biothings.client:querying 79001-80000 ...
INFO:biothings.client:querying 80001-81000 ...
INFO:biothings.client:querying 81001-82000 ...
INFO:biothings.client:querying 82001-83000 ...
INFO:biothings.client:querying 83001-84000 ...
INFO:biothings.client:querying 84001-85000 ...
INFO:biothings.client:querying 85001-86000 ...
INFO:biothings.client:querying 86001-87000 ...
INFO:biothings.client:querying 87001-88000 ...
INFO:biothings.client:querying 88001-89000 ...
INFO:biothings.client:querying 89001-90000 ...
INFO:biothings.client:querying 90001-91000 ...
INFO:biothings.client:querying 91001-92000 ...
INFO:biothings.client:querying 92001-93000 ...
INFO:biothings.client:querying 93001-94000 ...
INFO:biothings.client:querying 94001-95000 ...
INFO:biothings.client:querying 95001-96000 ...
INFO:biothings.client:querying 96001-97000 ...
INFO:biothings.client:querying 97001-98000 ...
INFO:biothings.client:querying 98001-99000 ...
INFO:biothings.client:querying 99001-100000 ...
INFO:biothings.client:querying 100001-101000 ...
INFO:biothings.client:querying 101001-102000 ...
INFO:biothings.client:querying 102001-103000 ...
INFO:biothings.client:querying 103001-104000 ...
INFO:biothings.client:querying 104001-105000 ...
INFO:biothings.client:querying 105001-106000 ...
INFO:biothings.client:querying 106001-107000 ...
INFO:biothings.client:querying 107001-108000 ...
INFO:biothings.client:querying 108001-109000 ...
INFO:biothings.client:querying 109001-110000 ...
INFO:biothings.client:querying 110001-111000 ...
INFO:biothings.client:querying 111001-112000 ...
INFO:biothings.client:querying 112001-113000 ...
INFO:biothings.client:querying 113001-114000 ...
INFO:biothings.client:querying 114001-115000 ...
INFO:biothings.client:querying 115001-116000 ...
INFO:biothings.client:querying 116001-117000 ...
INFO:biothings.client:querying 117001-118000 ...
INFO:biothings.client:querying 118001-119000 ...
INFO:biothings.client:querying 119001-120000 ...
INFO:biothings.client:querying 120001-121000 ...
INFO:biothings.client:querying 121001-122000 ...
INFO:biothings.client:querying 122001-123000 ...
INFO:biothings.client:querying 123001-124000 ...
INFO:biothings.client:querying 124001-125000 ...
INFO:biothings.client:querying 125001-126000 ...
INFO:biothings.client:querying 126001-127000 ...
INFO:biothings.client:querying 127001-128000 ...
INFO:biothings.client:querying 128001-129000 ...
INFO:biothings.client:querying 129001-130000 ...
INFO:biothings.client:querying 130001-131000 ...
INFO:biothings.client:querying 131001-132000 ...
INFO:biothings.client:querying 132001-133000 ...
INFO:biothings.client:querying 133001-134000 ...
INFO:biothings.client:querying 134001-135000 ...
INFO:biothings.client:querying 135001-136000 ...
INFO:biothings.client:querying 136001-137000 ...
INFO:biothings.client:querying 137001-138000 ...
INFO:biothings.client:querying 138001-139000 ...
INFO:biothings.client:querying 139001-140000 ...
INFO:biothings.client:querying 140001-141000 ...
INFO:biothings.client:querying 141001-142000 ...
INFO:biothings.client:querying 142001-143000 ...
INFO:biothings.client:querying 143001-144000 ...
INFO:biothings.client:querying 144001-145000 ...
INFO:biothings.client:querying 145001-146000 ...
INFO:biothings.client:querying 146001-147000 ...
INFO:biothings.client:querying 147001-148000 ...
INFO:biothings.client:querying 148001-149000 ...
INFO:biothings.client:querying 149001-150000 ...
INFO:biothings.client:querying 150001-151000 ...
INFO:biothings.client:querying 151001-152000 ...
INFO:biothings.client:querying 152001-153000 ...
INFO:biothings.client:querying 153001-154000 ...
INFO:biothings.client:querying 154001-155000 ...
INFO:biothings.client:querying 155001-156000 ...
INFO:biothings.client:querying 156001-157000 ...
INFO:biothings.client:querying 157001-158000 ...
INFO:biothings.client:querying 158001-159000 ...
INFO:biothings.client:querying 159001-160000 ...
INFO:biothings.client:querying 160001-161000 ...
INFO:biothings.client:querying 161001-162000 ...
INFO:biothings.client:querying 162001-163000 ...
INFO:biothings.client:querying 163001-164000 ...
INFO:biothings.client:querying 164001-165000 ...
INFO:biothings.client:querying 165001-166000 ...
INFO:biothings.client:querying 166001-167000 ...
INFO:biothings.client:querying 167001-168000 ...
INFO:biothings.client:querying 168001-169000 ...
INFO:biothings.client:querying 169001-170000 ...
INFO:biothings.client:querying 170001-171000 ...
INFO:biothings.client:querying 171001-172000 ...
INFO:biothings.client:querying 172001-173000 ...
INFO:biothings.client:querying 173001-174000 ...
INFO:biothings.client:querying 174001-175000 ...
INFO:biothings.client:querying 175001-176000 ...
INFO:biothings.client:querying 176001-177000 ...
INFO:biothings.client:querying 177001-178000 ...
INFO:biothings.client:querying 178001-179000 ...
INFO:biothings.client:querying 179001-180000 ...
INFO:biothings.client:querying 180001-181000 ...
INFO:biothings.client:querying 181001-182000 ...
INFO:biothings.client:querying 182001-183000 ...
INFO:biothings.client:querying 183001-184000 ...
INFO:biothings.client:querying 184001-185000 ...
INFO:biothings.client:querying 185001-186000 ...
INFO:biothings.client:querying 186001-187000 ...
INFO:biothings.client:querying 187001-188000 ...
INFO:biothings.client:querying 188001-188753 ...
INFO:biothings.client:Finished.
WARNING:biothings.client:83 input query terms found dup hits:	[('ENST00000303728', 2), ('ENST00000320865', 2), ('ENST00000362058', 2), ('ENST00000400419', 2), ('E
WARNING:biothings.client:5496 input query terms found no hit:	['ENST00000035383', 'ENST00000053469', 'ENST00000062104', 'ENST00000074304', 'ENST00000155858', 'ENS
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [ ]:
pd_ds.index[:10]

Index(['ARF5', 'M6PR', 'ESRRA', 'FKBP4', 'CYP26B1', 'NDUFAF7', 'FUCA2',
       'DBNDD1', 'HS3ST1', 'SEMA3F'],
      dtype='object', name='gene_symbol')

In [ ]:
pd_ds.to_csv("PD_geneSymbol.csv")
hd.to_csv("HD_geneSymbol.csv")

**4. DUPLICATE GENE REMOVAL**

In [ ]:
def remove_duplicate_genes(df):
    # drop rows with missing or empty gene symbols
    df = df[~df.index.isna()]
    df = df[df.index != ""]

    # average duplicates
    df = df.groupby(df.index).mean()
    return df

In [ ]:
ad = remove_duplicate_genes(ad)
ms = remove_duplicate_genes(ms)
pd_ds = remove_duplicate_genes(pd_ds)
hd = remove_duplicate_genes(hd)

In [ ]:
ad = remove_duplicate_genes(ad)
ms = remove_duplicate_genes(ms)
pd_ds = remove_duplicate_genes(pd_ds)
hd = remove_duplicate_genes(hd)

In [ ]:
print("AD:", ad.shape)
print("MS:", ms.shape)
print("PD:", pd_ds.shape)
print("HD:", hd.shape)

AD: (23520, 173)
MS: (23520, 29)
PD: (31508, 16)
HD: (23118, 69)

**5. COMMON GENE INTERSECTION**

In [ ]:
common_genes = (
    set(ad.index)
    & set(ms.index)
    & set(pd_ds.index)
    & set(hd.index)
)

print("Number of common genes:", len(common_genes))

Number of common genes: 14784

In [ ]:
common_genes = sorted(common_genes)

ad_c = ad.loc[common_genes]
ms_c = ms.loc[common_genes]
pd_c = pd_ds.loc[common_genes]
hd_c = hd.loc[common_genes]

In [ ]:
print(ad_c.shape, ms_c.shape, pd_c.shape, hd_c.shape)

(14784, 173) (14784, 29) (14784, 16) (14784, 69)

In [ ]:
ad_c.to_csv("AD_commonGenes.csv")
ms_c.to_csv("MS_commonGenes.csv")
pd_c.to_csv("PD_commonGenes.csv")
hd_c.to_csv("HD_commonGenes.csv")

In [ ]:
pd.Series(common_genes, name="geneSymbol").to_csv(
    "COMMON_GENES_14784.csv", index=False
)

**6. z- Score STANDARDIZATION**

In [ ]:
ad = pd.read_csv("AD_commonGenes.csv", index_col=0)
ms = pd.read_csv("MS_commonGenes.csv", index_col=0)
pd_ds = pd.read_csv("PD_commonGenes.csv", index_col=0)
hd = pd.read_csv("HD_commonGenes.csv", index_col=0)

print(ad.shape, ms.shape, pd_ds.shape, hd.shape)

(14784, 173) (14784, 29) (14784, 16) (14784, 69)

In [ ]:
from scipy.stats import zscore
import pandas as pd

ad_z = pd.DataFrame(
    zscore(ad, axis=1, nan_policy='omit'),
    index=ad.index,
    columns=ad.columns
)

ms_z = pd.DataFrame(
    zscore(ms, axis=1, nan_policy='omit'),
    index=ms.index,
    columns=ms.columns
)

pd_z = pd.DataFrame(
    zscore(pd_ds, axis=1, nan_policy='omit'),
    index=pd_ds.index,
    columns=pd_ds.columns
)

hd_z = pd.DataFrame(
    zscore(hd, axis=1, nan_policy='omit'),
    index=hd.index,
    columns=hd.columns
)

In [ ]:
ad_z.mean(axis=1).head()
ad_z.std(axis=1).head()

gene_symbol
A1BG     1.002903
A1CF     1.002903
A2M      1.002903
A2ML1    1.002903
A2MP1    1.002903
dtype: float64

In [ ]:
ad_z.to_csv("AD_zscore.csv")
ms_z.to_csv("MS_zscore.csv")
pd_z.to_csv("PD_zscore.csv")
hd_z.to_csv("HD_zscore.csv")

In [ ]:
ad_z.std(axis=1).describe()

count    1.478400e+04
mean     1.002903e+00
std      3.568780e-13
min      1.002903e+00
25%      1.002903e+00
50%      1.002903e+00
75%      1.002903e+00
max      1.002903e+00
dtype: float64

In [ ]:
ad_z.iloc[0, :10]
ad_z.iloc[1, :10]

GSM300166    2.016834
GSM300167    0.208010
GSM300168   -2.682012
GSM300169   -2.934985
GSM300170   -2.792433
GSM300171   -3.506179
GSM300172   -2.396952
GSM300173    0.079872
GSM300174   -0.357549
GSM300175   -0.376347
Name: A1CF, dtype: float64